//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptek_Program.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineToFirm
    {
        public int ID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<int> FirmID { get; set; }
    
        public virtual Firms Firms { get; set; }
        public virtual Medicines Medicines { get; set; }
    }
}
