//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptek_Program.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptekApp : DbContext
    {
        public AptekApp()
            : base("name=AptekApp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<MedicineToFirm> MedicineToFirm { get; set; }
        public virtual DbSet<MedicineToTag> MedicineToTag { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
