//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptek_Program.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public int Amount { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
